### ISSUE TITLE
Bargain Eats section is about parking?

### ISSUE THREAD

**Issue by abeyer** [pycascades/welcome-wagon-2019#17]
https://pycascades-welcome-wagon-2019.readthedocs.io/en/latest/dining_guide.html#id3

Doesn't say anything about food...maybe this was supposed to go somewhere else? Otherwise lets just delete that section.

**Comment by Mariatta** [comment]
Maybe we meant to have a Bargain Eats section but never finished it.

We can move the parking into to the Seattle travel guide.
Would you be able to prepare the PR with this change?

**Comment by ndenny** [comment]
Removed the section, think it was just an old copy-paste error.
