### ISSUE TITLE
Problem with github webhook to trigger new build

### ISSUE THREAD

**Issue by ndenny** [pycascades/welcome-wagon-2019#6]
I think because I created the readthedocs project with a different repo originally, the webhook isn't working correctly.
It appears it should be set to: readthedocs.org/api/v2/webhook/pycascades-welcome-wagon-2019/64919/ - but I don't seem to have access to that bit of this repo.

**Comment by Mariatta** [comment]
Seems like it is rendering fine? https://welcome-wagon-2019.readthedocs.io/en/latest/dining_guide.html contains your latest changes I think.

**Comment by ndenny** [comment]
Yeah, I think that's a build I triggered manually, unless I'm not understanding this correctly?

**Comment by Mariatta** [comment]
I think there were two different readthedocs projects pointing to the same repo. What is your readthedocs account?

**Comment by ndenny** [comment]
Ah yeah, I created a new project in readthedocs:
https://readthedocs.org/projects/pycascades-welcome-wagon-2019/
I’ll try and add you as a maintainer, if we want to keep that. Last year’s one has 2018 in the URL, so I thought we’d start a-fresh.

**Comment by Mariatta** [comment]
Cool, I've added you as admin to this repo, that'll give you access to edit the webhook.

**Comment by Mariatta** [comment]
My readthedocs username is mariatta. (I recall case matters ...)

**Comment by ndenny** [comment]
The latest changes triggered the build! We can close this, thanks for your help!
