### ISSUE TITLE
Travis CI build fails on commit

### ISSUE THREAD

**Issue by ndenny** [pycascades/welcome-wagon-2019#7]
This one is out of my wheelhouse, but from what I can tell, the command it's using for the build is correct and when I run it locally, it passes.
Not a high priority, the site is building on readthedocs without any issues.

**Comment by Mariatta** [comment]
There's a warning: title underline is too short:
https://travis-ci.com/pycascades/welcome-wagon-2019/builds/98647235
![screen shot 2019-01-25 at 10 22 47 am](https://user-images.githubusercontent.com/5844587/51764911-34ce7780-208b-11e9-8129-4db4cad9dc1f.png)
